// Import all your JavaScript files here
import './components/RegisterForm.js';
import './components/Map.js';
import './components/Modal.js';
import './components/EventGeni.js';
import './components/widgets/Pagewidget.js'
import './components/widgets/Sectionwidget.js'
import './components/widgets/Stickynavbarwidget.js'
import './components/widgets/Popupwidget.js'
import './components/MultipleSectionData.js'
import './components/templates/GridView.js'
import './components/templates/ListView.js'
import './components/templates/listcardstyles/ListCard1.js'  
import './components/templates/listcardstyles/ListCard2.js'  
import './components/templates/listcardstyles/ListCard3.js'  
import './components/templates/CaraouselView.js'  
import './components/templates/Popup.js'  
import './components/templates/HeroBanner.js'
import './components/templates/cardstyles/Card1.js';
import './components/templates/cardstyles/Card2.js';
import './components/templates/cardstyles/Card3.js';
import './components/templates/HeroBannerAndListView.js'
import './components/templates/HeroBannerAndGridView.js'
import './components/templates/CaraouselAndGridView.js'
import './components/templates/CaraouselAndListView.js'
import './components/templates/ScrollView.js'